### ISSUE TITLE
Docker coeman-par-local

### ISSUE THREAD

**Issue by JGasp** [NLeSC/Massive-PotreeConverter#16]
Host: Windows 10 Hyper-V. 
Using docker image mentioned in readme [docker hub image](https://hub.docker.com/r/oscarmartinezrubi/massive-potreeconverter/).

When i try to execute `coeman-par-local -d . -c /data1/ParallelPotreeConverter.xml -e /data1/execution -n 4` it fails to run PotreeConverter with log message:

> ERROR: filesystem error: cannot canonicalize: No such file or directory [/data1/execution/tile_0_0_potree_converter/PotreeConverter] [/data1/execution/tile_0_0_potree_converter]

This message is same in every execution. I tried to run PotreeConverter i get similar result which is why i think bug is in PotreeConverter. But if i download PotreeConverter and use it in win10 it works. This is why i think bug is exclusive to Linux OS.

Using PotreeConverter in windows 10 i converted tiles in shared folder, but merge in docker image then failed.

**Comment by pksorensen** [comment]
Got similar issues

```
C:\Users\pks> docker run -v D:/PKS/potree/ekbi/dist:/data1 -v D:/PKS/potree/ekbi/tiles:/data2 oscarmartinezrubi/massive-potreeconverter coeman-par-local -d / -c /data1/ParallelPotreeConve
rter.xml -e /data1/execution -n 16
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/parcommands/run_parcommands_local.py", line 22, in runChild
    utils_execution.initExecutionFolderLocal(executionFolderCommandAbsPath, requiredElements)
  File "/usr/local/lib/python2.7/dist-packages/pycoeman/utils_execution.py", line 39, in initExecutionFolderLocal
    os.symlink(elementAbsPath , os.path.join(executionFolderAbsPath, os.path.basename(elementAbsPath)))
OSError: [Errno 22] Invalid argument
```
