### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by fenglupeter** [NLeSC/Massive-PotreeConverter#17]
pip3 install .
Processing ~/Massive-PotreeConverter
    Complete output from command python setup.py egg_info:
    Installation could not be done: PDAL could not be found.

pip3 install pdal
Collecting pdal
  Using cached PDAL-1.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-99kx84k8/pdal/setup.py", line 126, in <module>
        raise Exception(message % (built_major, running_major))
    Exception: Version mismatch. PDAL Python support was compiled against version 2.x but setup is running version is 3.x.

**Comment by fenglupeter** [comment]
just copy the pdal binary to /usr/bin/
