### ISSUE TITLE
mpc-merge-all Problems

### ISSUE THREAD

**Issue by Raquel0** [NLeSC/Massive-PotreeConverter#27]
Hi!! It's me again :nerd_face: 

I i'm trying to convert some different pointclouds and, some of them work perfectly, but other point clouds are giving me new problems:
when i run mpc-merge-all with all the arguments and following all the preveius steps, i sometimes get execution failed, but not always.
The times this doesn't work, what i see on command line is that the process simply gets stopped with no error message. Searching through generated files, everything is fine but a file. The .log file asociated to the last tile it tried to convert.
  
`Input Potree Octtree A:  MyPATH/Potree-OctTrees-merged/merged_7`
`Input Potree Octtree B:  MyPATH/Potree-OctTrees/tile_7_5_potree`
`Output Potree Octtree:  MyPATH/Potree-OctTrees-merged/merged_8`
`mkdir -p MyPATH/Potree-OctTrees-merged/merged_8`
`lasinfo MyPATH/Potree-OctTrees/tile_7_5_potree/data/r/rlas -nc -nv -nco`
`mkdir -p MyPATH/Potree-OctTrees-merged/merged_8/data/r`
**`Execution failed!`**
`Traceback (most recent call last):`
`  File "/home/raquel/.local/lib/python3.6/site-packages/pympc/merge_potree_all.py", line 70, in main`
`    run(args.input, args.output, args.move)`
`  File "/home/raquel/.local/lib/python3.6/site-packages/pympc/merge_potree_all.py", line 44, in run`
`    merge_potree.run(octTreeAInputFolder, octTreeBInputFolder, octTreeOutputFolder, moveFiles)`
`  File "/home/raquel/.local/lib/python3.6/site-packages/pympc/merge_potree.py", line 157, in run`
`    joinNode('r', dataA + '/r', dataB + '/r', dataO + '/r', hierarchyStepSize, extension, cmcommand)`
`  File "/home/raquel/.local/lib/python3.6/site-packages/pympc/merge_potree.py", line 44, in joinNode`
`    hasNodeB = (i < numChildrenB) and (hrcB[level][i] > 0)`
**`TypeError: '>' not supported between instances of 'NoneType' and 'int'`**

Any idea why, or how to solve this??

Thank you very much!!!!!!! :smile:

**Comment by AlbionS** [comment]
@Raquel0  
Hi,
Did you solve this case ? I have the same issue !
